---
title: Corredores biológicos en el cono sur bajo el contexto de cambio climático utilizando
  modelación basada en agentes
author: "Derek Corcoran"
date: '`r Sys.Date()`'
output:
  word_document: default
  pdf_document:
    fig_caption: yes
bibliography: bibliography.bib
---

#Formulación de la Propuesta
##Introducción

Uno de los principales objetivos de la ecología es el entender la distribución de los organismos [@elton_animal_1927] lo que se define como los límites geográficos de su presencia, y donde es generalmente reconocido que la extensión del rango de una especie es proporcional a la amplitud de su nicho [@gaston_structure_2003; @peterson_ecological_2011]. 

Las variables que determinan y limitan de la distribución de una especie pueden ser tanto bióticos (incapacidad de reproducirse o sobrevivir en ciertas condiciones) o bióticos (influenciado por depredadores, parásitos y/o mutualistas) [@gaston_geographic_2009]. A pesar de ser una característica básica de los organismos es extremadamente complejo de estudiar, en parte por ser un concepto dinámico ya que el rango de una especie puede cambiar por alteraciones en los factores que limitan el rango o debido a cambios evolutivos de la especie que modifican estos límites [@holt_evolutionary_2003; @macarthur_geographical_1972; @macarthur_theory_1968]. Dentro de los factores que más han modificado el rango de dispersión de especies se encuentran la sobrexplotación de los recursos naturales, el cambio climático global [@parmesan_beyond_2013; @parmesan_poleward_1999, @lenoir2008significant], la fragmentación de hábitat [@bright_habitat_1993] y la introducción de especies [@mooney_evolutionary_2001]. Es por esto que se le atribuye al ser humano la responsabilidad de ser uno de los principales moduladores del rango de las especies [@vitousek_beyond_1994].

Una herramienta ampliamente utilizada para el estudio de los rangos geográficos de las especies es la modelación de distribución de especies [@hirzel_habitat_2008; @peterson_ecological_2011; @soberon_grinnellian_2007]. Esta metodología que fue desarrollada en 1984 [@gillison1984gradient], además de ser utilizada para generar distribuciones actuales, se ha ocupado para predecir las distribuciones potenciales de las especies producto del cambio climático bajo distintos escenarios propuestos para el futuro [@baker_role_2000; maiorano_building_2013].

Bajo esta línea de estudio, el cambio climático y la fragmentación del hábitat se combinan formando una nueva problemática. Por efecto del cambio climático se predice que las especies cambien su área de distribución [@chen_rapid_2011, @lenoir2008significant], sin embargo es necesario que se dispersen hacia esta nueva área de distribucion potencial que ha de ser modelada. Para evitar problemas de conservación de especies debido a que estas no puedan dispersarse a áreas óptimas futuras, se requiere de corredores biológicos [@nunez_connectivity_2013; @rosenberg_biological_1997]. Debido a la presencia de hábitats fragmentados producto del proceso de urbanización, industrialización o cambios de uso de suelo, las especies no siempre podrán llegar a esta nueva área óptima. Esto podría incluso ser verse incrementado, ya que algunas actividades económicas tales como la agricultura, también deberán modificar su area de acción para acomodarse a estas nuevas condiciones climáticas y con esto utilizar nuevas áreas de distribución o corredores de estas especies[@hannah2013climate]. Estos corredores conectarían áreas de distribución actual con áreas de distribución potencial futura, así como también permitirán el flujo genético entre poblaciones distantes, lo cual también debe ser modelado para considerar las necesidades de hábitat la especie, las variables que una especie puede soportar, la capacidad y tasa de dispersión, entre otros factores. La planificación y creación de estos corredores biológicos corresponden a medidas adaptativas frente a las variaciones ambientales ya que son acciones que reducen los impactos al cambio climático global [@book_499349]. 


##Herramientas actuales de conservacion: las áreas protegidas

El concepto de "área protegida"" se define en Chile como un área definida geográficamente que ha sido designada o regulada y administrada con la finalidad de alcanzar objetivos específicos de conservación [@DiversidadBiologica1995]. El Sistema Nacional de áreas Protegidas del Estado de Chile o SNASPE contempla 102 unidades de protección abarcando un total de 14.715.570 ha que representan un 19,3% de la superficie nacional [@MedioAmbiente1995]. Dentro de estas areas existen tres entidades adminstradas por el Estado a cargo de la Corporación Nacional Forestal, CONAF: 1) los Parques Nacionales que buscan protección y conservacion de ambientes particulares, 2) las Reservas Nacionales que conservan en base a la utilización de recursos y 3) los Monumentos Naturales que intentan conservar objetos específicos o especies definidas en los cuales solo se puede realizar investigacion cientifica o inspecciones gubernamentales [@ConvencionFloraFauna1967]. Los Parques Nacionales abarcan una superfice nacional de 12,1%, las Reservas Nacionales 7,1% y los Monumentos Naturales solo un 0,04% [@CONAF_Restauracion_2015].

A pasar de los intentos por conservar en el país, sólo tomando en cuenta condiciones actuales, se ha determinado que aproximadamente un 13% de las especies chilenas no se encuentran consideradas por las áreas protegidas de Chile [@marquet_how_2004; tognelli_how_2008]. Junto con esto, las soluciones que se toman a nivel nacional pueden ser ineficientes comparativamente con soluciones a nivel regional [@levin_biodiversity_2014; @mazor_collaboration_2013; mazor_large-scale_2014], donde se ha encontrado ahorros de hasta un 66% en costos económicos para proteger la misma cantidad de recursos naturales si se hace de forma coordinada entre varias naciones que si se hace como nación individual [@mazor_collaboration_2013].

Posibles soluciones a esta descoordinacion de esfuerzos se han descrito en torno a la creación y mantención de areas protegidas privadas [@pauchard2002protected] y la necesidad de conectividad entre ellas de forma fisica o funcional para asegurar recursos que puedan sustentar poblaciones viables [@simonetti2002conservando]. Estas áreas
podrían comprender parques privados de mayores extensiones para conservación, la acción de los dueños de tierras [@kamal2014should], contemplando campos de cultivos e incluso jardines de casas [@gaston2005urban; @thompson2003urban] , parques y hasta sitios abandonados [@savard2000biodiversity; @gibson1998brownfield; @eyre2003beetles]. Estudios de biodiversidad urbana ya han demostrado que existe cierta conectividad entre estas áreas ya que por ejemplo en Inglatera no se han observado diferencias en la abundancia y riqueza de especies de visitantes de flores entre ambientes urbanos, campos de cultivo y reservas naturales [@baldock2015uk].

Una posible planificación para el establecimiento de corredores biológicos debiera abarcar estos factores para solventar poblaciones viables


Existen numerosos ejemplos de estudios en los cuales se estudian los corredores potenciales de una o unas pocas especies [@alagador_climate_2016; @gregory2014forecasts ; @cushman2013evaluating], pero hay pocos casos que han trabajado con varias especies y en estos trabajos se ha realizado a una escala muy local [@beier2007linkage]. Recientemente se ha acuñado el término "enlace" para definir el conscenso de los corredores biológicos de multiples especies [@beier2008forks], lo cual permitiría planificar para la conservacion de diversidad y no sólo de especies en particular. 

Este proyecto propone considerar la modelación de distribución actual de especies, la distribución potencial de especies considerando escenarios de cambio climático [@IPCCWG1PhysicalStocker2013] y la modelación basada en agentes [@valbuena_agent-based_2010], para determinar la posibilidad de dispersión de las especies desde la distribución actual y la potencial en el futuro. Se generarán estos modelos para chile y para todos los paises del cono sur, y se generaran concensos para ambos escenarios para determinar si los corredores resultantes son los mismos.


###Objetivos

- Desarrollo de una metodología estadística robusta, y el desarrollo de un software libre en R que permita la aplicación de estos análisis en todos los casos necesarios. 

- Probar las metodologías para 100 especies presentes en Chile.

- Analizar si dado el uso de suelo actual de Chile, es posible que las especies estudiadas utilicen sus nuevos rangos y si las rutas propuestas son posibles.
 

##Métodos


Se generará una base de datos con la totalidad de especies de Fauna terrestre de Chile (No migratorias) esta base de datos tendrá las siguientes características:
 
- El área (kms cuadrados) de su rango de acuerdo a IUCN
- El centroide de su distribución
- La categoría de conservación de acuerdo a la IUCN como variable ordinal (En peligro crítico, En peligro (EN), Vulnerable (VU), Casi amenazada (NT), Preocupación menor (LC))
- Phylum de cada especie
 
Luego de generar esta base de datos se clasificaran las especies en cinco grupos usando agrupación de k-means. Posterior a eso se caracterizará cada grupo y se seleccionarán aleatoriamente X especies por cada grupo para ser modelada.

Se verificará si dado el uso de suelo actual de Chile, es posible que las especies estudiadas utilicen sus nuevos rangos y si las rutas propuestas son posibles.

#Planificacion

```{r, echo=FALSE, message=FALSE, warning=FALSE, out.extra='angle=90', out.width='10in', fig.width=14, fig.height=9, cache = TRUE}
library(plan)
library(lubridate)
data("gantt")
description <- c("Preparacion base de datos", "Clasificacion de especies", "Modelacion distribucion actual", "Modelacion distribucion futura", "Congreso Socecol", "Desarrollo e implementación del\n Packete BioCorridoR para R" ,"Desarrollo modelos basados\n en agentes", "Generación de corredores\n para Chile", "Asistencia Congreso UseR!", "Publicación sobre Paquete R","Generacion de corredores\n Para Sudamerica", "Publicación corredores\n de Chile" , "Desarrollo de plataforma Shiny", "Publicación concenso corredores\n Chile, Sudamerica")
start <- as.POSIXct(dmy(c("01/03/2017","01/03/2017", "01/07/2017", "01/07/2017","01/11/2017","01/07/2017", "02/01/2018", "02/01/2018", "15/06/2018", "1/10/2018", "01/01/2019", "02/01/2019", "01/08/2019", "01/09/2019")))
end <- as.POSIXct(dmy(c("30/06/2017","30/06/2017", "31/12/2017","31/12/2017","15/11/2017","31/12/2018", "31/07/2018", "31/07/2018", "7/07/2018", "31/12/2018", "31/07/2018", "30/04/2019", "30/10/2019", "31/12/2019")))

key <- c(1:length(description))

done <- rep(0, length(description))

neededBy <- rep(NA, length(description))

GanttPostDoc <- list(key, description, start, end, done, neededBy)

names(GanttPostDoc) <- names(gantt)
class(GanttPostDoc) <- c("gantt")

plot(GanttPostDoc, time.labels.by="4 months", time.lines.by="1 year", grid.lty = 2)
```

###Preparación base de datos:
Recolección de caracteristicas y polígonos de distribución de todas las especies animales terrestres de Chile desde bases de datos digitales y extraccion de caracteristicas tales como área, centroide y estado de conservación entre otras.

###Clasificación de especies:
Utilizando la base de datos previamente creada, se clasificará a las especies en cinco clusters para hacer un muestreo representativo de 20 especies dentro de cada uno de ellos, estas especies serán utilizadas para las modelaciones posteriores. 

###Modelación distribución actual:
Para cada una de las especies seleccionadas se generará un modelo de distribución de especies basado en presencias filtradas de la base de datos del GBIF [@flemons2007web] y en características climáticas extraídas de Worldclim [@hijmans_very_2005]

###Modelación distribución futura:
Para cada una de las especies se proyectarán los modelos generados a condiciones futuras para determinar su distribución de acuerdo a los modelos de la IPCC

###Congreso Socecol:
Se presentarán los resultados de las modelaciones presentes y futuras en el congreso binacional de ecología

###Desarrollo modelos basados en agentes:
Utilizando el programa Netlogo [@sklar2007netlogo], se generarán modelos basados en agentes para simular el desplazamiento de las especies desde sus rangos actuales a los predichos por los modelos de distribución de especies

###Desarrollo e implementación del Packete BioCorridoR para R:
Desarrollo de paquete para el entorno de R que tendrá funciones que permitirán generar análisis para cualquier grupo de especies deseado por usuarios para generar los mismos análisis generados por esta investigación.

###Generación de corredores para Chile:
Generación de corredores para Chile tomando en cuenta las rutas de desplazamiento más utilizadas por las especies seleccionadas. 

###Asistencia Congreso UseR!:
Presentación de la primera versión del paquete BioCorridoR en el congreso más importante de la comunidad de desarrolladores de R.

###Publicación sobre paquete BioCorridoR:
Se presentará el paquete BioCorridoR en el Journal of Statistical Sofware.

###Generación de corredores para Sudamérica:
Se probará un nuevo escenario donde las especies analizadas podrán utilizar como parte del corredor países vecinos, se evaluará las diferencias de efectividad de planificación nacional contrastada con planificación regional (Sudamérica).

###Publicación corredores de Chile:
Publicación de análisis de corredores biológicos concenso planificados para Chile.

###Desarrollo de plataforma Shiny
Desarrollo de paltaforma de Shiny Apps para ejemplificar e implementar uso interactivo de BioCorridoR

###Publicación concenso corredores en Chile y Sudamerica
Publicación de análisis de corredores biológicos concenso para el Cono sur y su comparación con los generados para Chile

#Trabajo Adelantado

Se han generado algoritmos para extraer poligonos de presencia de especies desde la pagina web de la IUCN, y a partir de ella extraer la información necesaria para la clasificación de especies, esto a sido testeado para los Mamíferos de Chile, posteriormente en base a esto se generó un nuevo algoritmo para extraer en base a esta tabla los puntos de presencia de estas epecies para la GBIF.

#Referencias